[package]
name = "decimal"
version = "0.4.0"
authors = ["Alkis Evlogimenos <alkis@evlogimenos.com>"]
build = "build.rs"
description = "Decimal floating point arithmetic for Rust"
repository = "https://github.com/alkis/decimal"
documentation = "https://alkis.github.io/decimal"
keywords = ["decimal", "decNumber"]
license = "Apache-2.0"

[dependencies]
bitflags = "~0.5"
libc = "~0.2"
ord_subset = { optional = true, version = "~1.2" }
rustc-serialize = { optional = true, version = "~0.3" }
decimal-macros = { optional = true, path = "decimal-macros/" }

[features]
default = ["ord_subset", "rustc-serialize"]
constant_macros = ["decimal-macros"]

[build-dependencies]
gcc = "~0.3"
